modified the backend documentation file
InventorsDev/inventor-backend pull request #21
Opened 2024-06-19 19:24 UTC by CodeGiant1

I modified the backend documentation by removing the nestjs template from the documentation.

2024-07-19 19:35 UTC, willypelz requested changes
This have merge conflicts

2024-07-24 19:51 UTC, CodeGiant1 commented
> This have merge conflicts

I have resolved the conflicts. @willypelz

2025-04-11 17:41 UTC, willypelz commented on package.json
> +    "@nestjs/schedule": "^4.1.1",
@DennisTemoye why do we have the nestjs/schedule brought into the code?

2025-04-11 17:44 UTC, willypelz commented
This PR is having some conflicts @DennisTemoye can you fix this and would be good to be merged.

- [] Package-lock.json
- [] src/users/users.controller.ts
- [] src/users/users.service.ts

2025-05-22 02:25 UTC, Tonykaynoni commented on src/users/users.service.ts
> +      .exec();
This PR title says modify the backend documentation, it might make sense to move this change to a separate PR or add some description on the PR on these changes and add unit test. Nicely done.

2026-05-28 20:23 UTC, closed without merging