created post blog module
InventorsDev/inventor-backend pull request #45
Opened 2024-11-23 18:26 UTC by onochukwu

2025-04-14 12:25 UTC, onochukwu commented
i have pushed the updated file sir

2025-05-20 20:26 UTC, willypelz commented
Reopening this because we need the blog work, the frontend is working on it. @snebo @onochukwu Pls let us resolve this and let the frontend integrate the application.

2025-05-20 20:27 UTC, willypelz commented
@onochukwu There is conflict on this PR. Please let us resolve

2025-05-20 20:32 UTC, willypelz commented on package-lock.json
@onochukwu can you remove the packe-lock.json, so we dont overide the repo with your local configuration.

2025-05-20 20:33 UTC, willypelz commented on postblog
@onochukwu why do we have this? seems it is a mistake. can it be removed.

2025-05-20 20:34 UTC, willypelz commented on src/shared/auth/guards/jwt.postcomment.guard.ts
> +      //logger.log("available roles:", userRole);
Can this comment be removed? @onochukwu

2025-05-20 20:35 UTC, willypelz commented on src/shared/auth/guards/jwt.post.guard.ts
> +      //logger.log("available roles:", userRole);
Can this comment be removed? @onochukwu

2025-05-21 19:10 UTC, willypelz commented on postblog
@onochukwu can this be removed file? seams not used

2025-05-22 01:51 UTC, Tonykaynoni commented on src/shared/auth/guards/jwt.event.users.guard.ts
> +      if (!hasRequiredRoles(userRoles, [UserRole.USER, UserRole.POST_USER])) {
This should never be edited for post user @willypelz, this guard is for event users only.

2025-05-22 02:14 UTC, Tonykaynoni requested changes
Nice work @onochukwu🔥, I added some comments that you should consider.

2025-05-22 02:14 UTC, Tonykaynoni commented on src/blog/postcomment/dto/postComment.dto.ts
> +  photo?: string;
Nice work thinking about this, but all these properties shouldn't be needed for a post comment.
we don't want users to upload images to comment, and generally i think we shouldn't allow comments on post for now, I don't see the need. Many stuff that will be posted on the blog should be details about previous / upcoming events. We can bring post comment in when we have member login/registration, that way it would easy to keep track of who added the comment and also enforce that only registered members can add comment.

2025-05-22 02:14 UTC, Tonykaynoni commented on src/blog/post/post.service.ts
> +    );
🔥🔥🔥🔥🔥🔥🔥

2025-05-22 02:14 UTC, Tonykaynoni commented on src/blog/post/post.service.ts
> +    );
Nice.

2025-05-22 02:14 UTC, Tonykaynoni commented on src/blog/post/post.controller.ts
> +  }
Only admins should be able to soft delete a post after it has been approved.

2025-05-22 02:14 UTC, Tonykaynoni commented on src/blog/post/post.controller.ts
> +  }
Only admins should also be able to update an approved post.
If the post is not approved post user can update it.

2025-05-22 02:14 UTC, Tonykaynoni commented on src/blog/post/post.controller.ts
> +export class PostController {
There should be a get post by list of status, so that frontend won't have to filter out deleted post or unapproved post.

2025-05-22 02:14 UTC, Tonykaynoni commented on src/shared/auth/guards/jwt.post.guard.ts
> +export class JwtPostUserGuard extends AuthGuard('jwt-user') {
Make sense 🔥👌🏼

2025-05-22 02:14 UTC, Tonykaynoni commented on src/shared/auth/guards/jwt.postcomment.guard.ts
> +}
As mentioned above, we won't need this and when we bring in the comment feature for members, all user type will be able to add comment on a post.

2025-05-28 16:08 UTC, willypelz approved these changes
Looks good. Pulled on local and works well. pushing this batch out so the frontend would start integration. More feedback would come on another PR.

2025-05-28 16:09 UTC, merged

2025-05-28 16:30 UTC, onochukwu commented on src/blog/postcomment/dto/postComment.dto.ts
> +  photo?: string;
I have deleted the comment folder sir

2025-05-28 18:29 UTC, Tonykaynoni commented on src/blog/post/post.controller.ts
> +  }
No auth guard on this, someone could call this API to view even unapproved post